### PR TITLE
check errno inside tinydir_file_open (fixes #58)

### LINKED ISSUE #58: tinydir_file_open not works on win7
Always returns `-1` because of checking `errno` inside function.

Example: https://github.com/staticlibs/staticlib_tinydir/blob/1.2.0/src/path.cpp#L176

### PR DESCRIPTION
**Pull request by sergw**
#58
`_tsplitpath_s` returns errno_t which should to be check
instead of `(void) _tsplitpath`

### CODE REVIEW

File: tinydir.h [hunk 1]
```diff
@@ -658,19 +658,29 @@ int tinydir_file_open(tinydir_file *file, const _tinydir_char_t *path)
...
 		_tsplitpath(
 			path,
 			drive_buf,
 			dir_name_buf,
 			file_name_buf,
 			ext_buf);
+
+		if (errno)
+		{
+			errno = EINVAL;
```
Comment (cxong) [inline tinydir.h]: this line isn't necessary anymore, `_tsplitpath` only uses `EINVAL` according to the docs.
This also means this `if (errno)` block doesn't need to be moved inside the `#ifdef` block.

Comment (sergw) [reply tinydir.h]: The problem described by issue #58 is in `if (errno)`. When I check return value of `_tsplitpath_s` it was zero, but errno is set already.
According to docs `_tsplitpath`:
> If path is NULL, the invalid parameter handler is invoked, as described in Parameter Validation. If execution is allowed to continue, errno is set to EINVAL and the function returns EINVAL.

`_tsplitpath` sets `errno` and looks like `_tsplitpath` is not `(void)`
and from docs `_tsplitpath_s`:
> Return Value
Zero if successful; an error code on failure.

May be we need to check retval? not `errno`?
